# This is a basic workflow to help you get started with Actions

name: Build livox_sdk_vendor

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: ros:foxy
